/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PikaApiRouteImport } from './routes/pika-api'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedV2RouteImport } from './routes/_authenticated-v2'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PikaApiIndexRouteImport } from './routes/pika-api.index'
import { Route as PikaApiSplatRouteImport } from './routes/pika-api.$'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'
import { Route as ApiPublicRenderTickRouteImport } from './routes/api/public/render-tick'
import { Route as ApiAssetIdRouteImport } from './routes/api/asset.$id'
import { Route as AuthenticatedStudioProjectIdRouteImport } from './routes/_authenticated/studio.$projectId'
import { Route as AuthenticatedV2V2LibraryRouteImport } from './routes/_authenticated-v2.v2.library'
import { Route as AuthenticatedV2V2JobsRouteImport } from './routes/_authenticated-v2.v2.jobs'
import { Route as AuthenticatedV2V2HomeRouteImport } from './routes/_authenticated-v2.v2.home'
import { Route as AuthenticatedV2V2AppsRouteImport } from './routes/_authenticated-v2.v2.apps'
import { Route as AuthenticatedV2V2StudioIndexRouteImport } from './routes/_authenticated-v2.v2.studio.index'
import { Route as AuthenticatedV2V2ProjectsIndexRouteImport } from './routes/_authenticated-v2.v2.projects.index'
import { Route as AuthenticatedV2V2StudioProjectIdRouteImport } from './routes/_authenticated-v2.v2.studio.$projectId'
import { Route as AuthenticatedV2V2ProjectsProjectIdRouteImport } from './routes/_authenticated-v2.v2.projects.$projectId'

const PikaApiRoute = PikaApiRouteImport.update({
  id: '/pika-api',
  path: '/pika-api',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedV2Route = AuthenticatedV2RouteImport.update({
  id: '/_authenticated-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PikaApiIndexRoute = PikaApiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PikaApiRoute,
} as any)
const PikaApiSplatRoute = PikaApiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PikaApiRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicRenderTickRoute = ApiPublicRenderTickRouteImport.update({
  id: '/api/public/render-tick',
  path: '/api/public/render-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetIdRoute = ApiAssetIdRouteImport.update({
  id: '/api/asset/$id',
  path: '/api/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioProjectIdRoute =
  AuthenticatedStudioProjectIdRouteImport.update({
    id: '/studio/$projectId',
    path: '/studio/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedV2V2LibraryRoute =
  AuthenticatedV2V2LibraryRouteImport.update({
    id: '/v2/library',
    path: '/v2/library',
    getParentRoute: () => AuthenticatedV2Route,
  } as any)
const AuthenticatedV2V2JobsRoute = AuthenticatedV2V2JobsRouteImport.update({
  id: '/v2/jobs',
  path: '/v2/jobs',
  getParentRoute: () => AuthenticatedV2Route,
} as any)
const AuthenticatedV2V2HomeRoute = AuthenticatedV2V2HomeRouteImport.update({
  id: '/v2/home',
  path: '/v2/home',
  getParentRoute: () => AuthenticatedV2Route,
} as any)
const AuthenticatedV2V2AppsRoute = AuthenticatedV2V2AppsRouteImport.update({
  id: '/v2/apps',
  path: '/v2/apps',
  getParentRoute: () => AuthenticatedV2Route,
} as any)
const AuthenticatedV2V2StudioIndexRoute =
  AuthenticatedV2V2StudioIndexRouteImport.update({
    id: '/v2/studio/',
    path: '/v2/studio/',
    getParentRoute: () => AuthenticatedV2Route,
  } as any)
const AuthenticatedV2V2ProjectsIndexRoute =
  AuthenticatedV2V2ProjectsIndexRouteImport.update({
    id: '/v2/projects/',
    path: '/v2/projects/',
    getParentRoute: () => AuthenticatedV2Route,
  } as any)
const AuthenticatedV2V2StudioProjectIdRoute =
  AuthenticatedV2V2StudioProjectIdRouteImport.update({
    id: '/v2/studio/$projectId',
    path: '/v2/studio/$projectId',
    getParentRoute: () => AuthenticatedV2Route,
  } as any)
const AuthenticatedV2V2ProjectsProjectIdRoute =
  AuthenticatedV2V2ProjectsProjectIdRouteImport.update({
    id: '/v2/projects/$projectId',
    path: '/v2/projects/$projectId',
    getParentRoute: () => AuthenticatedV2Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pika-api': typeof PikaApiRouteWithChildren
  '/apps': typeof AuthenticatedAppsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/pika-api/$': typeof PikaApiSplatRoute
  '/pika-api/': typeof PikaApiIndexRoute
  '/v2/apps': typeof AuthenticatedV2V2AppsRoute
  '/v2/home': typeof AuthenticatedV2V2HomeRoute
  '/v2/jobs': typeof AuthenticatedV2V2JobsRoute
  '/v2/library': typeof AuthenticatedV2V2LibraryRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/render-tick': typeof ApiPublicRenderTickRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/v2/projects/$projectId': typeof AuthenticatedV2V2ProjectsProjectIdRoute
  '/v2/studio/$projectId': typeof AuthenticatedV2V2StudioProjectIdRoute
  '/v2/projects/': typeof AuthenticatedV2V2ProjectsIndexRoute
  '/v2/studio/': typeof AuthenticatedV2V2StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/pika-api/$': typeof PikaApiSplatRoute
  '/pika-api': typeof PikaApiIndexRoute
  '/v2/apps': typeof AuthenticatedV2V2AppsRoute
  '/v2/home': typeof AuthenticatedV2V2HomeRoute
  '/v2/jobs': typeof AuthenticatedV2V2JobsRoute
  '/v2/library': typeof AuthenticatedV2V2LibraryRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/render-tick': typeof ApiPublicRenderTickRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/v2/projects/$projectId': typeof AuthenticatedV2V2ProjectsProjectIdRoute
  '/v2/studio/$projectId': typeof AuthenticatedV2V2StudioProjectIdRoute
  '/v2/projects': typeof AuthenticatedV2V2ProjectsIndexRoute
  '/v2/studio': typeof AuthenticatedV2V2StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated-v2': typeof AuthenticatedV2RouteWithChildren
  '/login': typeof LoginRoute
  '/pika-api': typeof PikaApiRouteWithChildren
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/pika-api/$': typeof PikaApiSplatRoute
  '/pika-api/': typeof PikaApiIndexRoute
  '/_authenticated-v2/v2/apps': typeof AuthenticatedV2V2AppsRoute
  '/_authenticated-v2/v2/home': typeof AuthenticatedV2V2HomeRoute
  '/_authenticated-v2/v2/jobs': typeof AuthenticatedV2V2JobsRoute
  '/_authenticated-v2/v2/library': typeof AuthenticatedV2V2LibraryRoute
  '/_authenticated/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/render-tick': typeof ApiPublicRenderTickRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_authenticated-v2/v2/projects/$projectId': typeof AuthenticatedV2V2ProjectsProjectIdRoute
  '/_authenticated-v2/v2/studio/$projectId': typeof AuthenticatedV2V2StudioProjectIdRoute
  '/_authenticated-v2/v2/projects/': typeof AuthenticatedV2V2ProjectsIndexRoute
  '/_authenticated-v2/v2/studio/': typeof AuthenticatedV2V2StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pika-api'
    | '/apps'
    | '/library'
    | '/projects'
    | '/api/chat'
    | '/pika-api/$'
    | '/pika-api/'
    | '/v2/apps'
    | '/v2/home'
    | '/v2/jobs'
    | '/v2/library'
    | '/studio/$projectId'
    | '/api/asset/$id'
    | '/api/public/render-tick'
    | '/studio/'
    | '/v2/projects/$projectId'
    | '/v2/studio/$projectId'
    | '/v2/projects/'
    | '/v2/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/apps'
    | '/library'
    | '/projects'
    | '/api/chat'
    | '/pika-api/$'
    | '/pika-api'
    | '/v2/apps'
    | '/v2/home'
    | '/v2/jobs'
    | '/v2/library'
    | '/studio/$projectId'
    | '/api/asset/$id'
    | '/api/public/render-tick'
    | '/studio'
    | '/v2/projects/$projectId'
    | '/v2/studio/$projectId'
    | '/v2/projects'
    | '/v2/studio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated-v2'
    | '/login'
    | '/pika-api'
    | '/_authenticated/apps'
    | '/_authenticated/library'
    | '/_authenticated/projects'
    | '/api/chat'
    | '/pika-api/$'
    | '/pika-api/'
    | '/_authenticated-v2/v2/apps'
    | '/_authenticated-v2/v2/home'
    | '/_authenticated-v2/v2/jobs'
    | '/_authenticated-v2/v2/library'
    | '/_authenticated/studio/$projectId'
    | '/api/asset/$id'
    | '/api/public/render-tick'
    | '/_authenticated/studio/'
    | '/_authenticated-v2/v2/projects/$projectId'
    | '/_authenticated-v2/v2/studio/$projectId'
    | '/_authenticated-v2/v2/projects/'
    | '/_authenticated-v2/v2/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticatedV2Route: typeof AuthenticatedV2RouteWithChildren
  LoginRoute: typeof LoginRoute
  PikaApiRoute: typeof PikaApiRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiAssetIdRoute: typeof ApiAssetIdRoute
  ApiPublicRenderTickRoute: typeof ApiPublicRenderTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pika-api': {
      id: '/pika-api'
      path: '/pika-api'
      fullPath: '/pika-api'
      preLoaderRoute: typeof PikaApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated-v2': {
      id: '/_authenticated-v2'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pika-api/': {
      id: '/pika-api/'
      path: '/'
      fullPath: '/pika-api/'
      preLoaderRoute: typeof PikaApiIndexRouteImport
      parentRoute: typeof PikaApiRoute
    }
    '/pika-api/$': {
      id: '/pika-api/$'
      path: '/$'
      fullPath: '/pika-api/$'
      preLoaderRoute: typeof PikaApiSplatRouteImport
      parentRoute: typeof PikaApiRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/render-tick': {
      id: '/api/public/render-tick'
      path: '/api/public/render-tick'
      fullPath: '/api/public/render-tick'
      preLoaderRoute: typeof ApiPublicRenderTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$id': {
      id: '/api/asset/$id'
      path: '/api/asset/$id'
      fullPath: '/api/asset/$id'
      preLoaderRoute: typeof ApiAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/$projectId': {
      id: '/_authenticated/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof AuthenticatedStudioProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated-v2/v2/library': {
      id: '/_authenticated-v2/v2/library'
      path: '/v2/library'
      fullPath: '/v2/library'
      preLoaderRoute: typeof AuthenticatedV2V2LibraryRouteImport
      parentRoute: typeof AuthenticatedV2Route
    }
    '/_authenticated-v2/v2/jobs': {
      id: '/_authenticated-v2/v2/jobs'
      path: '/v2/jobs'
      fullPath: '/v2/jobs'
      preLoaderRoute: typeof AuthenticatedV2V2JobsRouteImport
      parentRoute: typeof AuthenticatedV2Route
    }
    '/_authenticated-v2/v2/home': {
      id: '/_authenticated-v2/v2/home'
      path: '/v2/home'
      fullPath: '/v2/home'
      preLoaderRoute: typeof AuthenticatedV2V2HomeRouteImport
      parentRoute: typeof AuthenticatedV2Route
    }
    '/_authenticated-v2/v2/apps': {
      id: '/_authenticated-v2/v2/apps'
      path: '/v2/apps'
      fullPath: '/v2/apps'
      preLoaderRoute: typeof AuthenticatedV2V2AppsRouteImport
      parentRoute: typeof AuthenticatedV2Route
    }
    '/_authenticated-v2/v2/studio/': {
      id: '/_authenticated-v2/v2/studio/'
      path: '/v2/studio'
      fullPath: '/v2/studio/'
      preLoaderRoute: typeof AuthenticatedV2V2StudioIndexRouteImport
      parentRoute: typeof AuthenticatedV2Route
    }
    '/_authenticated-v2/v2/projects/': {
      id: '/_authenticated-v2/v2/projects/'
      path: '/v2/projects'
      fullPath: '/v2/projects/'
      preLoaderRoute: typeof AuthenticatedV2V2ProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedV2Route
    }
    '/_authenticated-v2/v2/studio/$projectId': {
      id: '/_authenticated-v2/v2/studio/$projectId'
      path: '/v2/studio/$projectId'
      fullPath: '/v2/studio/$projectId'
      preLoaderRoute: typeof AuthenticatedV2V2StudioProjectIdRouteImport
      parentRoute: typeof AuthenticatedV2Route
    }
    '/_authenticated-v2/v2/projects/$projectId': {
      id: '/_authenticated-v2/v2/projects/$projectId'
      path: '/v2/projects/$projectId'
      fullPath: '/v2/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedV2V2ProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedV2Route
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedStudioProjectIdRoute: typeof AuthenticatedStudioProjectIdRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedStudioProjectIdRoute: AuthenticatedStudioProjectIdRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticatedV2RouteChildren {
  AuthenticatedV2V2AppsRoute: typeof AuthenticatedV2V2AppsRoute
  AuthenticatedV2V2HomeRoute: typeof AuthenticatedV2V2HomeRoute
  AuthenticatedV2V2JobsRoute: typeof AuthenticatedV2V2JobsRoute
  AuthenticatedV2V2LibraryRoute: typeof AuthenticatedV2V2LibraryRoute
  AuthenticatedV2V2ProjectsProjectIdRoute: typeof AuthenticatedV2V2ProjectsProjectIdRoute
  AuthenticatedV2V2StudioProjectIdRoute: typeof AuthenticatedV2V2StudioProjectIdRoute
  AuthenticatedV2V2ProjectsIndexRoute: typeof AuthenticatedV2V2ProjectsIndexRoute
  AuthenticatedV2V2StudioIndexRoute: typeof AuthenticatedV2V2StudioIndexRoute
}

const AuthenticatedV2RouteChildren: AuthenticatedV2RouteChildren = {
  AuthenticatedV2V2AppsRoute: AuthenticatedV2V2AppsRoute,
  AuthenticatedV2V2HomeRoute: AuthenticatedV2V2HomeRoute,
  AuthenticatedV2V2JobsRoute: AuthenticatedV2V2JobsRoute,
  AuthenticatedV2V2LibraryRoute: AuthenticatedV2V2LibraryRoute,
  AuthenticatedV2V2ProjectsProjectIdRoute:
    AuthenticatedV2V2ProjectsProjectIdRoute,
  AuthenticatedV2V2StudioProjectIdRoute: AuthenticatedV2V2StudioProjectIdRoute,
  AuthenticatedV2V2ProjectsIndexRoute: AuthenticatedV2V2ProjectsIndexRoute,
  AuthenticatedV2V2StudioIndexRoute: AuthenticatedV2V2StudioIndexRoute,
}

const AuthenticatedV2RouteWithChildren = AuthenticatedV2Route._addFileChildren(
  AuthenticatedV2RouteChildren,
)

interface PikaApiRouteChildren {
  PikaApiSplatRoute: typeof PikaApiSplatRoute
  PikaApiIndexRoute: typeof PikaApiIndexRoute
}

const PikaApiRouteChildren: PikaApiRouteChildren = {
  PikaApiSplatRoute: PikaApiSplatRoute,
  PikaApiIndexRoute: PikaApiIndexRoute,
}

const PikaApiRouteWithChildren =
  PikaApiRoute._addFileChildren(PikaApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticatedV2Route: AuthenticatedV2RouteWithChildren,
  LoginRoute: LoginRoute,
  PikaApiRoute: PikaApiRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiAssetIdRoute: ApiAssetIdRoute,
  ApiPublicRenderTickRoute: ApiPublicRenderTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
